# Generated by Django 4.1.5 on 2023-01-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('buydate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=150)),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=200)),
                ('package', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='insurance_app.packages')),
            ],
        ),
    ]
