# Generated by Django 4.1.5 on 2023-01-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_alter_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/covers'),
        ),
        migrations.AlterField(
            model_name='users',
            name='package',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='insurance_app.packages'),
        ),
    ]
